/**
 * demoData provides some fake data
 */
const demoData = [
    {
      "title":'White Camoflague Cargo Pants',
      "subtitle":'Fashion inspo Outfits',
      "description":' Cargo pants have been used as an outfit by British military, and taking the influence from them, the cargo pants have made their way to mainstream fashion. Be it men or women, they wear cargo pants for various events, or for casual outings. In short, cargo pants can be easily pulled off in many way.',
      "img":'https://i.pinimg.com/736x/6a/de/9c/6ade9c616219f887184c880d66c21b3b.jpg',
      "catagories":'cargo',
      "price":9.99,
      "keys":"100123"
    },
    
    {
      "title":'Baggy Cargo',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu9EQJShwFiAfnNww0FDwfvR7YH_5Ni5R1Cw&usqp=CAU',
      "catagories":'cargo',
      "price":12.99,
      "keys":"1001234",
    },
    {
      "title":'Aesthetic combo',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-2amQrA47_VMhWxJNxmw3veJ4FeARiPImyQ&usqp=CAU',
      "catagories":'cargo',
      "price":23.99,
      "keys":"100145234",
    },
    {
      "title":'Caro Pants',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2EOh4jEyyIYgz0MUoTkk1eobiS9Vvu3LCUA&usqp=CAU',
      "catagories":'cargo',
      "price":15.99,
      "keys":"10012347",
    },
    {
      "title":'Baggy Cargo Joggers',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTihKeXQBsy-StBB8_deKhaeHjcUEjam6fS1w&usqp=CAU',
      "catagories":'cargo',
      "price":7.99,
      "keys":"1001423",
    },
    {
      "title":'90s Retro',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7_ipbvTjV-5yAYQkplP9dWkdwSmsBWn0x56BRWI4iuwsBmogV0xgxNm3w0a6y8pCQwxc&usqp=CAU',
      "catagories":'cargo',
      "price":19.99,
      "keys":"1770123",
    },
    {
      "title":'Pink three piece set',
      "subtitle":'Street-Wear',
      "description":'There’s one big difference; this time, classic styles are reinvented in oversized and loud colors, activewear, and streetwear styles.',
      "img":'https://thevou.com/wp-content/uploads/2021/05/Current-fashion-trends-wtvox.com-Pastel-01.jpg',
      "catagories":'street',
      "price":9.99,
      "keys":"108453",
    },
    {
      "title":'Grey Track-Suit',
      "subtitle":'How we dream about our style',
      "description":'there’s one big difference; this time, classic styles are reinvented in oversized and loud colors, activewear, and streetwear styles.',
      "img":'https://t4.ftcdn.net/jpg/05/00/84/99/360_F_500849991_EX8gIm81ZMfla6wU6jGgbenE4yJNeos1.jpg',
      "catagories":'street',
      "price":12.99,
      "keys":"199123",
    },
    {
      "title":'Baggy Set',
      "subtitle":'How we dream about our style',
      "description":'there’s one big difference; this time, classic styles are reinvented in oversized and loud colors, activewear, and streetwear styles.',
      "img":'https://i.pinimg.com/736x/55/38/ec/5538ec30613f63d07fb96b843a832e33.jpg',
      "catagories":'street',
      "price":23.99,
      "keys":"10483",
    },
    {
      "title":'OverSized Street Wears',
      "subtitle":'How we dream about our style',
      "description":'there’s one big difference; this time, classic styles are reinvented in oversized and loud colors, activewear, and streetwear styles.',
      "img":'https://i.pinimg.com/736x/02/cb/ae/02cbae807907d2dddcc974d8f0c9b801.jpg',
      "catagories":'street',
      "price":15.99,
      "keys":"107484",
    },
    {
      "title":'Denim Jackets',
      "subtitle":'How we dream about our style',
      "description":'there’s one big difference; this time, classic styles are reinvented in oversized and loud colors, activewear, and streetwear styles.',
      "img":'https://www.pinkvilla.com/files/styles/amp_metadata_content_image/public/ma_main_1_1.jpg',
      "catagories":'street',
      "price":7.99,
      "keys":"114414",
    },
    {
      "title":'Long Coat',
      "subtitle":'How we dream about our style',
      "description":'there’s one big difference; this time, classic styles are reinvented in oversized and loud colors, activewear, and streetwear styles.',
      "img":'https://thevou.com/wp-content/uploads/2021/05/Current-fashion-trends-wtvox.com-Matching-sets-01.jpg',
      "catagories":'street',
      "price":19.99,
      "keys":"1178123",
    },
    {
      "title":'White - Oversized ',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://assets.vogue.com/photos/5c4771cf3476db3b7bd26959/master/w_320%2Cc_limit/07-baggy-pants.jpg',
      "catagories":'oversized',
      "price":9.99,
      "keys":"1001234854",
    },
    {
      "title":'Elegant Style',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://i.pinimg.com/564x/2b/38/f3/2b38f37aa9d084574bbd8e9075c6cacb.jpg',
      "catagories":'oversized',
      "price":12.99,
      "keys":"10012374874",
    },
    {
      "title":'PullOver',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfJddzhns7nJaTdEGQPRa4dBwQekK41iPDDg&usqp=CAU',
      "catagories":'oversized',
      "price":23.99,
      "keys":"10014564723",
    },
    {
      "title":'Polo Tees',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYHxa72Mm0d9A33x7HImSXxwwYZ-XiqMgh8owTKcmY23C1Ywzyd8iMD82P7VeH8x8Z_uE&usqp=CAU',
      "catagories":'oversized',
      "price":15.99,
      "keys":"1001778623",
    },
    {
      "title":'Printed Heart',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRroQ834kbum4nhuxI_eX0SwrGWE6JvWY_EqA&usqp=CAU',
      "catagories":'oversized',
      "price":7.99,
      "keys":"100123545444",
    },
    {
      "title":'Red Aesthetics',
      "subtitle":'How we dream about our style',
      "description":'What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language',
      "img":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVL2uqylSgvtiFsCVTEN3Ql-jTq_VbSDu2iA&usqp=CAU',
      "catagories":'oversized',
      "price":19.99,
      "keys":"100142447423",
    },
  ]
  export default demoData;